---
### **Question 1**
> **Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like:**
> - **a)** Addition of 2 in all the element
> - **b)** Multiply 3 with all the elements
> - **c)** Divide every element by 2


In [8]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print("Original 1D Array:", arr)

res_add = arr + 2
print("\na) Addition of 2 in all elements (arr + 2):")
print(res_add)

res_mul = arr * 3
print("\nb) Multiply 3 with all elements (arr * 3):")
print(res_mul)

res_div = arr / 2
print("\nc) Divide every element by 2 (arr / 2):")
print(res_div)


Original 1D Array: [10 20 30 40 50]

a) Addition of 2 in all elements (arr + 2):
[12 22 32 42 52]

b) Multiply 3 with all elements (arr * 3):
[ 30  60  90 120 150]

c) Divide every element by 2 (arr / 2):
[ 5. 10. 15. 20. 25.]


---
### **Question 2**
> **Q.2 Questions on Basic NumPy Array:**
> - **a)** Reverse the NumPy array: `arr = np.array([1, 2, 3, 6, 4, 5])`
> - **b)** Find the most frequent value and their indice(s) in the following arrays:
>   - **i.** `x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])`
>   - **ii.** `y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])`


In [9]:
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]

print("Original Array:", arr)
print("Reversed Array (via slicing arr[::-1]):", reversed_arr)
print("Reversed Array (via np.flip):", np.flip(arr))


Original Array: [1 2 3 6 4 5]
Reversed Array (via slicing arr[::-1]): [5 4 6 3 2 1]
Reversed Array (via np.flip): [5 4 6 3 2 1]


In [10]:
def find_most_frequent_and_indices(arr, arr_name):
    unique_vals, counts = np.unique(arr, return_counts=True)
    max_freq = np.max(counts)
    modes = unique_vals[counts == max_freq]
    
    print(f"\nAnalysis for array '{arr_name}': {arr.tolist()}")
    for mode in modes:
        indices = np.where(arr == mode)[0]
        print(f"  • Most Frequent Value: {mode} (Count: {max_freq})")
        print(f"    Indice(s): {indices.tolist()}")

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
find_most_frequent_and_indices(x, "x")

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
find_most_frequent_and_indices(y, "y")



Analysis for array 'x': [1, 2, 3, 4, 5, 1, 2, 1, 1, 1]
  • Most Frequent Value: 1 (Count: 5)
    Indice(s): [0, 5, 7, 8, 9]

Analysis for array 'y': [1, 1, 1, 2, 3, 4, 2, 4, 3, 3]
  • Most Frequent Value: 1 (Count: 3)
    Indice(s): [0, 1, 2]
  • Most Frequent Value: 3 (Count: 3)
    Indice(s): [4, 8, 9]


---
### **Question 3**
> **Q.3 For the given 2-D array `arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])`, access elements using row and column indices as follows:**
> - **a)** Access 1st row, 2nd column
> - **b)** Access 3rd row, 1st column


In [11]:
arr_2d = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("Given 2-D Array:\n", arr_2d)

elem_a = arr_2d[0, 1]
print(f"\na) 1st row, 2nd column (arr_2d[0, 1]): {elem_a}")

elem_b = arr_2d[2, 0]
print(f"b) 3rd row, 1st column (arr_2d[2, 0]): {elem_b}")


Given 2-D Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

a) 1st row, 2nd column (arr_2d[0, 1]): 20
b) 3rd row, 1st column (arr_2d[2, 0]): 70


---
### **Question 4**
> **Q.4 Write program to create an 1-D NumPy array named `<<Your Name>>` with evenly spaced 25 numbers from 10 to 100 using `linspace()`. Print the dimensions of the array, shape, total elements, the data type of each element and total number of bytes consumed by the array. Find the transpose of this array using `reshape()` attribute. Can we do the same with `T` attribute?**


In [12]:
kavay_khurana = np.linspace(10, 100, 25)

print("Array kavay_khurana values:")
print(kavay_khurana)

print("\n" + "="*50)
print(f"1. Dimensions (ndim): {kavay_khurana.ndim}")
print(f"2. Shape: {kavay_khurana.shape}")
print(f"3. Total Elements (size): {kavay_khurana.size}")
print(f"4. Data Type (dtype): {kavay_khurana.dtype}")
print(f"5. Total Bytes Consumed (nbytes): {kavay_khurana.nbytes} bytes")
print("="*50)

transposed_reshaped = kavay_khurana.reshape(-1, 1)
print("\nTranspose of array represented as 2D Column Vector using reshape(-1, 1):")
print(f"Shape: {transposed_reshaped.shape}")
print(transposed_reshaped)


Array kavay_khurana values:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

1. Dimensions (ndim): 1
2. Shape: (25,)
3. Total Elements (size): 25
4. Data Type (dtype): float64
5. Total Bytes Consumed (nbytes): 200 bytes

Transpose of array represented as 2D Column Vector using reshape(-1, 1):
Shape: (25, 1)
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]


#### **Can we do the same with `T` attribute?**

**Detailed Explanation & Conceptual Justification:**
- **Behavior of `.T` on 1-D Array:**
  In NumPy, a 1-D array has only one axis (`ndim = 1`, shape `(25,)`). Transposing an array swaps its axes. Because there is no second axis to swap with, applying `.T` on a 1-D array returns the exact same 1-D array without any dimensional change.
- **Achieving Transpose with `.T`:**
  To perform a meaningful transpose with `.T`, we can convert the 1-D array into a 2-D row vector of shape `(1, 25)` using `kavay_khurana.reshape(1, -1)`. Then, `.T` will swap axis 0 and axis 1, converting the `(1, 25)` row vector into a `(25, 1)` column vector.


In [13]:
print("1. Direct .T on 1D array:")
print("   kavay_khurana.T shape:", kavay_khurana.T.shape)
print("   Are original and .T identical?", np.array_equal(kavay_khurana, kavay_khurana.T))

print("\n2. Using .T after shaping into 2D row vector (1, 25):")
row_vector = kavay_khurana.reshape(1, -1)
col_vector_T = row_vector.T
print("   Shape of (1, 25).T:", col_vector_T.shape)
print("   Matches reshape(-1, 1):", np.array_equal(transposed_reshaped, col_vector_T))


1. Direct .T on 1D array:
   kavay_khurana.T shape: (25,)
   Are original and .T identical? True

2. Using .T after shaping into 2D row vector (1, 25):
   Shape of (1, 25).T: (25, 1)
   Matches reshape(-1, 1): True


---
### **Question 5**
> **Q5. Create a 2-D Array of three rows and four columns, named `ucs420_<your_name>>` with following values – `10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35`. Compute the mean, median, max, min, unique elements. Reshape the array to four rows and three columns and name it as `reshaped_ucs420_<your_name>>`. Resize the array to two rows and three columns and name it as `resized_ucs420_<your_name>>`.**


In [14]:
values_list = [10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35]
ucs420_kavay_khurana = np.array(values_list).reshape(3, 4)

print("Original 2-D Array (ucs420_kavay_khurana) [3x4]:")
print(ucs420_kavay_khurana)

print("\n" + "="*45)
print("STATISTICAL COMPUTATIONS:")
print(f"  • Mean: {np.mean(ucs420_kavay_khurana):.2f}")
print(f"  • Median: {np.median(ucs420_kavay_khurana):.2f}")
print(f"  • Max Value: {np.max(ucs420_kavay_khurana)}")
print(f"  • Min Value: {np.min(ucs420_kavay_khurana)}")
print(f"  • Unique Elements: {np.unique(ucs420_kavay_khurana)}")
print("="*45)

reshaped_ucs420_kavay_khurana = ucs420_kavay_khurana.reshape(4, 3)
print("\nReshaped Array (4x3) [reshaped_ucs420_kavay_khurana]:")
print(reshaped_ucs420_kavay_khurana)
print("Shape:", reshaped_ucs420_kavay_khurana.shape)

resized_ucs420_kavay_khurana = np.resize(ucs420_kavay_khurana, (2, 3))
print("\nResized Array (2x3) [resized_ucs420_kavay_khurana]:")
print(resized_ucs420_kavay_khurana)
print("Shape:", resized_ucs420_kavay_khurana.shape)


Original 2-D Array (ucs420_kavay_khurana) [3x4]:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

STATISTICAL COMPUTATIONS:
  • Mean: 43.33
  • Median: 37.50
  • Max Value: 90
  • Min Value: 10
  • Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped Array (4x3) [reshaped_ucs420_kavay_khurana]:
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Shape: (4, 3)

Resized Array (2x3) [resized_ucs420_kavay_khurana]:
[[10 20 30]
 [40 50 60]]
Shape: (2, 3)
